### ISSUE TITLE
Cannot be opened

### ISSUE THREAD

**Issue by DoloFay** [iseahound/Vis2#15]
Hi i have many problem, the demo.ahk doesn't work, the libs don't wan't be opened

**Comment by iseahound** [comment]
1. Goto https://github.com/iseahound/Vis2/releases

2. Download the zip file. 
![image](https://user-images.githubusercontent.com/9779668/170716516-832b0ebc-a8bb-41b2-8994-8f73cd1d2339.png)

3. Extract the zip file to your desktop. 
![image](https://user-images.githubusercontent.com/9779668/170716825-bfc26fdf-de7e-4bdc-bf15-4656a69b9eaf.png)

4. Double Click demo.ahk
![image](https://user-images.githubusercontent.com/9779668/170716998-cedabd64-5d0f-40b7-9068-bdacb0145061.png)

**Comment by DoloFay** [comment]
This is what i do and this is my error 
![image](https://user-images.githubusercontent.com/78095921/170718300-1c188c73-2c50-4b42-a212-5fc42ab58246.png)

**Comment by iseahound** [comment]
You didn't follow my instructions. Sounds like you didn't unzip the entire
archive.
