### ISSUE TITLE
Question: will this be affected by monitor power saving mode?

### ISSUE THREAD

**Issue by thdoan** [iseahound/Vis2#16]
Hi, I'm testing this on a timer right now so that it scrapes a tiny part of the screen every second. My question is, what happens if my monitor goes into sleep mode -- will this continue to function, or does the monitor have to be on in order for it to do its OCR thing?

**Comment by iseahound** [comment]
That's not controlled by Vis2. You need to ensure your power saving functions are correctly set. In general, turning the monitor off does not affect image capture.
