### ISSUE TITLE
About the management of "Gdip_All" libary.

### ISSUE THREAD

**Issue by 00xSky** [iseahound/Vis2#18]
**I added the translation feature to the Vis2 OCR system, but I cannot use the "Btt/Gdip_All" library as regularly as you do.I tried to add my own function to the "class Vis2" field in Vis2.ahk, but I have basic knowledge of autohotkey and I couldn't understand how you use "tooltip" so I couldn't add it.**

**I request you to inform me about the regular display of Translation results at your convenient time. Thanks**

**Comment by iseahound** [comment]
It's not clear what you want - If you are building something using Vis2 you are free to modify the code.

**Comment by 00xSky** [comment]
Ok, I am using it by adding the following code. thanks

![image](https://user-images.githubusercontent.com/34361925/195189270-bff43bd4-f679-457c-8d9a-eaebbfeb85bc.png)

**Comment by iseahound** [comment]
You can also use [TextRender](https://github.com/iseahound/TextRender) for this. It contains several years' worth of improvements.  With that said however, `Vis2.Graphics.Subtitle.Render` is exceptionally well designed.
