### ISSUE TITLE
OCR([x, y, w, h]) relative to window?

### ISSUE THREAD

**Issue by marcspc** [iseahound/Vis2#6]
can I make OCR([x, y, w, h]) work relative to active window instead of screen?

**Comment by iseahound** [comment]
Yes. I believe it's OCR("A", "", [x,y,w,h]).

**Comment by obuw** [comment]
This doesn't seem to be working for me. I have a dual screen setup, and I'm failing to get OCR to work on any window in the second screen.

If I call OCR() and use the drag selection, it works fine. But if I try to call it using [x,y,w,h] parameters, it just reads from the first screen. To make regular ahk gui stuff work I can offset the x coordinates by 1920, but vis2 just throws an error if I try to do that.

I hope there is a simple solution to this problem? I'm sure there must be some kind of config setting for it, but the tesseract documentation is a nightmare to read through. Maybe I need to change the coordmode settings in the vis2 script?
